package com.walter.saiyansurvivor;

import android.content.Context;
import android.graphics.*;
import android.view.MotionEvent;
import android.view.View;
import java.util.*;

public class GameViewV3 extends View {
    private final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG), t=new Paint(Paint.ANTI_ALIAS_FLAG);
    private final Random r=new Random(); private final AudioEngine audio=new AudioEngine();
    private final ArrayList<E> es=new ArrayList<>(); private final ArrayList<B> bs=new ArrayList<>();
    private final ArrayList<O> os=new ArrayList<>(); private final ArrayList<C> cs=new ArrayList<>();
    private final ArrayList<F> fs=new ArrayList<>(); private final ArrayList<U> opts=new ArrayList<>();
    private float x,y,jx,jy,jbx,jby,hp=120,maxHp=120,xp=0,next=12,speed=330,dmg=1,pick=100,armor=0;
    private int lv=1,kills=0,ki=1,kame=0,disc=0,bomb=0,kai=0,ssj=0,radar=0,senzu=0;
    private boolean init,joy,dead,choose; private long start,lastFrame,lastSpawn,lastChest,lastBoss,lastKi,lastKame,lastDisc,lastBomb,bannerUntil;
    private String banner="SURVIVE!"; private float shift;

    public GameViewV3(Context c){super(c);t.setColor(Color.WHITE);audio.start();}
    @Override protected void onDetachedFromWindow(){audio.stop();super.onDetachedFromWindow();}
    @Override protected void onSizeChanged(int w,int h,int ow,int oh){if(!init){x=w*.5f;y=h*.58f;start=System.currentTimeMillis();lastFrame=System.nanoTime();init=true;}}
    @Override protected void onDraw(Canvas c){if(!init)return;long n=System.nanoTime();float dt=Math.min(.033f,(n-lastFrame)/1e9f);lastFrame=n;if(!dead&&!choose)update(dt);render(c);invalidate();}

    private void update(float dt){long now=System.currentTimeMillis(),elapsed=now-start;float jl=(float)Math.hypot(jx,jy);if(jl>1){float sx=jx/jl*speed*dt,sy=jy/jl*speed*dt;x+=sx;y+=sy;shift+=sx*.35f;}x=cl(x,35,getWidth()-35);y=cl(y,70,getHeight()-40);
        float intensity=Math.min(1f,elapsed/145000f+Math.min(.5f,es.size()/80f));for(E e:es)if(e.boss)intensity=1;audio.setIntensity(intensity);
        long sc=Math.max(120,650-elapsed/210);if(now-lastSpawn>sc){spawn(false,elapsed);if(elapsed>65000&&r.nextFloat()<.22)spawn(false,elapsed);lastSpawn=now;}if(elapsed>35000&&now-lastBoss>52000){spawn(true,elapsed);audio.sfx(AudioEngine.SFX_BOSS);show("BOSS APPROACHING!");lastBoss=now;}if(now-lastChest>25000){cs.add(new C(80+r.nextFloat()*(getWidth()-160),100+r.nextFloat()*(getHeight()-190)));lastChest=now;}
        fireWeapons(now);moveBullets(dt);moveEnemies(dt);collect(dt);}

    private void fireWeapons(long now){if(now-lastKi>Math.max(220,620-(ki-1)*65)){targetFire(0,1+(ki>=3?1:0)+(ki>=5?1:0));audio.sfx(AudioEngine.SFX_KI);lastKi=now;}if(kame>0&&now-lastKame>Math.max(1700,4300-kame*430)){targetFire(1,1);audio.sfx(AudioEngine.SFX_KAME);show("KAMEHAMEHA!");lastKame=now;}if(disc>0&&now-lastDisc>Math.max(1200,3200-disc*280)){targetFire(2,disc>=4?2:1);audio.sfx(AudioEngine.SFX_DISC);lastDisc=now;}if(bomb>0&&now-lastBomb>Math.max(2500,6200-bomb*420)){targetFire(3,1);audio.sfx(AudioEngine.SFX_BOMB);lastBomb=now;}}
    private void targetFire(int type,int amount){E q=nearest();if(q==null)return;float a=(float)Math.atan2(q.y-y,q.x-x);for(int i=0;i<amount;i++){float aa=a+(i-(amount-1)/2f)*.15f,sp=type==3?260:type==1?620:700,rr=type==3?20+bomb*3:type==1?16+kame*3:type==2?15+disc*2:9+ki,dd=(type==3?45+bomb*16:type==1?30+kame*13:type==2?18+disc*8:10+ki*4)*dmg;bs.add(new B(type,x,y,(float)Math.cos(aa)*sp,(float)Math.sin(aa)*sp,rr,dd,type==2?3+disc:type==1?2+kame/2:type==3?99:Math.max(0,ki-4)));}}
    private E nearest(){E q=null;float bd=Float.MAX_VALUE;for(E e:es){float d=dist(x,y,e.x,e.y);if(d<bd){bd=d;q=e;}}return q;}

    private void moveBullets(float dt){for(int i=bs.size()-1;i>=0;i--){B b=bs.get(i);b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<0||b.x<-100||b.x>getWidth()+100||b.y<-100||b.y>getHeight()+100){bs.remove(i);continue;}boolean rem=false;for(int j=es.size()-1;j>=0;j--){E e=es.get(j);if(dist(b.x,b.y,e.x,e.y)<b.r+e.r){e.hp-=b.d;b.hits++;fs.add(new F(e.x,e.y,"-"+(int)b.d));if(b.type==3){splash(b.x,b.y,70+bomb*15,b.d);rem=true;}if(e.hp<=0)kill(j,e);if(!rem&&b.hits>b.pierce)rem=true;if(rem)break;}}if(rem)bs.remove(i);}}
    private void splash(float xx,float yy,float rr,float dd){for(int j=es.size()-1;j>=0;j--){E e=es.get(j);if(dist(xx,yy,e.x,e.y)<rr+e.r){e.hp-=dd;if(e.hp<=0)kill(j,e);}}fs.add(new F(xx,yy,"BOOM"));}
    private void moveEnemies(float dt){for(E e:es){float dx=x-e.x,dy=y-e.y,d=(float)Math.max(1,Math.hypot(dx,dy));e.x+=dx/d*e.sp*dt;e.y+=dy/d*e.sp*dt;e.cd-=dt;if(d<e.r+22&&e.cd<=0){hp-=Math.max(1,e.touch-armor);e.cd=.7f;audio.sfx(AudioEngine.SFX_HIT);if(hp<=0){hp=0;dead=true;}}}for(int i=fs.size()-1;i>=0;i--){F f=fs.get(i);f.y-=35*dt;f.life-=dt;if(f.life<0)fs.remove(i);}}
    private void collect(float dt){for(int i=os.size()-1;i>=0;i--){O o=os.get(i);float d=dist(x,y,o.x,o.y);if(d<pick){o.x+=(x-o.x)*Math.min(1,dt*9);o.y+=(y-o.y)*Math.min(1,dt*9);}if(d<28){xp+=o.v;if(r.nextFloat()<.35)audio.sfx(AudioEngine.SFX_PICKUP);os.remove(i);levelCheck();}}for(int i=cs.size()-1;i>=0;i--){C c=cs.get(i);if(dist(x,y,c.x,c.y)<40){audio.sfx(AudioEngine.SFX_CHEST);randomUpgrade(true);cs.remove(i);}}}

    private void spawn(boolean boss,long elapsed){float xx,yy;int edge=r.nextInt(4);if(edge==0){xx=-45;yy=r.nextFloat()*getHeight();}else if(edge==1){xx=getWidth()+45;yy=r.nextFloat()*getHeight();}else if(edge==2){xx=r.nextFloat()*getWidth();yy=-45;}else{xx=r.nextFloat()*getWidth();yy=getHeight()+45;}float sc=1+elapsed/100000f;int type=boss?4:(elapsed<40000?0:elapsed<85000?(r.nextBoolean()?0:1):elapsed<130000?r.nextInt(3):r.nextInt(4));float rr=boss?38:18+type*2,h=boss?260*sc:(34+type*18)*sc,sp=boss?76:108-type*10,touch=boss?18:7+type*2;es.add(new E(xx,yy,type,h,rr,sp,touch,boss));}
    private void kill(int idx,E e){es.remove(idx);kills++;int n=e.boss?18:1+(e.type>=2?1:0);for(int i=0;i<n;i++)os.add(new O(e.x+r.nextInt(20)-10,e.y+r.nextInt(20)-10,e.boss?3:1));if(e.boss){cs.add(new C(e.x,e.y));show("BOSS DEFEATED!");}}
    private void levelCheck(){while(xp>=next){xp-=next;lv++;next=next*1.24f+5;presentChoices();break;}}
    private void presentChoices(){choose=true;audio.sfx(AudioEngine.SFX_LEVEL);opts.clear();ArrayList<String> pool=new ArrayList<>(Arrays.asList("ki","kame","disc","bomb","kai","senzu","radar","ssj"));Collections.shuffle(pool,r);for(int i=0;i<3;i++)opts.add(new U(pool.get(i)));}
    private void randomUpgrade(boolean chest){String[] a={"ki","kame","disc","bomb","kai","senzu","radar","ssj"};apply(a[r.nextInt(a.length)],chest);}
    private void apply(String id,boolean chest){String m=id;if(id.equals("ki")){ki=Math.min(6,ki+1);m="Ki Blast Lv "+ki;}else if(id.equals("kame")){kame=Math.min(5,kame+1);m="Kamehameha Lv "+kame;}else if(id.equals("disc")){disc=Math.min(5,disc+1);m="Kienzan Lv "+disc;}else if(id.equals("bomb")){bomb=Math.min(4,bomb+1);m="Genkidama Lv "+bomb;}else if(id.equals("kai")){kai++;speed+=25;m="Kaioken Lv "+kai;}else if(id.equals("senzu")){senzu++;maxHp+=18;hp=Math.min(maxHp,hp+38);m="Senzu Bean";}else if(id.equals("radar")){radar++;pick+=38;m="Dragon Radar Lv "+radar;}else{ssj++;dmg+=.22f;speed+=16;audio.sfx(AudioEngine.SFX_TRANSFORM);m=ssj==1?"SUPER SAIYAN!":"Super Saiyan Lv "+ssj;}choose=false;opts.clear();show((chest?"CHEST: ":"LEVEL UP: ")+m);}
    private void show(String s){banner=s;bannerUntil=System.currentTimeMillis()+1700;}

    private void render(Canvas c){drawBg(c);for(C q:cs)drawChest(c,q);for(O o:os){p.setColor(Color.rgb(90,230,255));c.drawCircle(o.x,o.y,7,p);}for(B b:bs)drawBullet(c,b);for(E e:es)drawEnemy(c,e);drawPlayer(c);for(F f:fs){t.setTextSize(18);t.setTextAlign(Paint.Align.CENTER);c.drawText(f.s,f.x,f.y,t);}drawHud(c);if(System.currentTimeMillis()<bannerUntil)drawBanner(c);if(choose)drawChoices(c);if(dead)drawDead(c);}
    private void drawBg(Canvas c){Paint g=p;g.setShader(new LinearGradient(0,0,0,getHeight(),new int[]{Color.rgb(18,35,82),Color.rgb(80,145,170),Color.rgb(132,188,102)},null,Shader.TileMode.CLAMP));c.drawRect(0,0,getWidth(),getHeight(),g);g.setShader(null);p.setColor(Color.argb(150,240,255,215));c.drawCircle(getWidth()*.82f,getHeight()*.15f,42,p);float gy=getHeight()*.64f;p.setColor(Color.rgb(111,170,92));c.drawRect(0,gy,getWidth(),getHeight(),p);for(int i=-1;i<8;i++){float xx=((i*190f)-shift*.18f)%(getWidth()+200);if(xx<-80)xx+=getWidth()+200;p.setColor(Color.rgb(54,88,100));Path m=new Path();m.moveTo(xx-90,gy);m.lineTo(xx,gy-100-(i%3)*22);m.lineTo(xx+90,gy);m.close();c.drawPath(m,p);}for(int i=0;i<6;i++){float xx=((i*230f+80)-shift*.35f)%(getWidth()+250);if(xx<-80)xx+=getWidth()+250;float yy=gy+12+(i%2)*25;p.setColor(Color.rgb(80,92,126));Path sp=new Path();sp.moveTo(xx-18,yy+45);sp.lineTo(xx,yy-38);sp.lineTo(xx+18,yy+45);sp.close();c.drawPath(sp,p);p.setColor(Color.rgb(72,150,108));c.drawOval(new RectF(xx-31,yy-54,xx+31,yy-18),p);}for(int i=0;i<9;i++){float xx=((i*140f)-shift*.6f)%(getWidth()+150);if(xx<0)xx+=getWidth()+150;p.setColor(Color.rgb(102,112,120));c.drawOval(new RectF(xx,gy+55+(i%3)*15,xx+34,gy+74+(i%3)*15),p);}}
    private void drawEnemy(Canvas c,E e){p.setColor(Color.argb(45,0,0,0));c.drawOval(new RectF(e.x-e.r,e.y+e.r*.6f,e.x+e.r,e.y+e.r),p);int[] col={Color.rgb(88,185,76),Color.rgb(130,82,190),Color.rgb(175,180,188),Color.rgb(220,118,182),Color.rgb(112,54,170)};p.setColor(col[e.type]);if(e.type==2)c.drawRoundRect(new RectF(e.x-e.r,e.y-e.r,e.x+e.r,e.y+e.r),7,7,p);else c.drawCircle(e.x,e.y,e.r,p);p.setColor(e.type==0?Color.BLACK:Color.rgb(255,230,120));c.drawCircle(e.x-6,e.y-5,3,p);c.drawCircle(e.x+6,e.y-5,3,p);if(e.boss){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(Color.RED);c.drawCircle(e.x,e.y,e.r+9,p);p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(190,20,20,20));c.drawRoundRect(new RectF(e.x-48,e.y-e.r-22,e.x+48,e.y-e.r-14),4,4,p);p.setColor(Color.RED);c.drawRoundRect(new RectF(e.x-48,e.y-e.r-22,e.x+48*Math.max(0,Math.min(1,e.hp/320f)),e.y-e.r-14),4,4,p);}}
    private void drawBullet(Canvas c,B b){if(b.type==0){p.setColor(Color.rgb(90,225,255));c.drawCircle(b.x,b.y,b.r,p);}else if(b.type==1){float a=(float)Math.atan2(b.vy,b.vx);p.setStrokeWidth(b.r);p.setColor(Color.argb(170,120,220,255));c.drawLine(b.x-(float)Math.cos(a)*110,b.y-(float)Math.sin(a)*110,b.x,b.y,p);p.setColor(Color.WHITE);c.drawCircle(b.x,b.y,b.r*.7f,p);}else if(b.type==2){p.setColor(Color.rgb(255,240,100));c.drawCircle(b.x,b.y,b.r,p);p.setColor(Color.WHITE);c.drawCircle(b.x,b.y,b.r*.55f,p);}else{p.setColor(Color.argb(100,120,210,255));c.drawCircle(b.x,b.y,b.r*1.8f,p);p.setColor(Color.WHITE);c.drawCircle(b.x,b.y,b.r,p);}}
    private void drawPlayer(Canvas c){int aura=ssj>0?Color.argb(110,255,225,70):kai>0?Color.argb(100,255,75,75):Color.argb(80,100,210,255);p.setColor(aura);c.drawCircle(x,y-5,36+ssj*3,p);p.setColor(Color.rgb(242,196,142));c.drawCircle(x,y-15,11,p);p.setColor(Color.rgb(242,122,38));c.drawRect(x-15,y-4,x+15,y+18,p);p.setColor(Color.rgb(38,70,200));c.drawRect(x-11,y+18,x-2,y+34,p);c.drawRect(x+2,y+18,x+11,y+34,p);Path h=new Path();h.moveTo(x-11,y-19);h.lineTo(x-18,y-33);h.lineTo(x-5,y-28);h.lineTo(x,y-42);h.lineTo(x+6,y-29);h.lineTo(x+17,y-36);h.lineTo(x+11,y-19);h.close();p.setColor(ssj>0?Color.rgb(255,225,80):Color.rgb(20,20,24));c.drawPath(h,p);}
    private void drawChest(Canvas c,C q){p.setColor(Color.rgb(108,58,28));c.drawRoundRect(new RectF(q.x-18,q.y-13,q.x+18,q.y+13),5,5,p);p.setColor(Color.rgb(244,185,55));c.drawRect(q.x-18,q.y-13,q.x+18,q.y-3,p);p.setColor(Color.YELLOW);c.drawRect(q.x-3,q.y-13,q.x+3,q.y+13,p);}
    private void drawHud(Canvas c){p.setColor(Color.argb(175,0,0,0));c.drawRoundRect(new RectF(14,12,410,105),14,14,p);t.setTextAlign(Paint.Align.LEFT);t.setTextSize(24);t.setColor(Color.WHITE);c.drawText("LV "+lv+"  Kills "+kills+"  "+time(),28,40,t);t.setTextSize(17);c.drawText("Ki "+ki+" • Kame "+kame+" • Kienzan "+disc+" • Genki "+bomb,28,65,t);p.setColor(Color.DKGRAY);c.drawRect(28,77,370,89,p);p.setColor(Color.RED);c.drawRect(28,77,28+342*(hp/maxHp),89,p);p.setColor(Color.DKGRAY);c.drawRect(14,getHeight()-20,getWidth()-14,getHeight()-9,p);p.setColor(Color.CYAN);c.drawRect(14,getHeight()-20,14+(getWidth()-28)*(xp/next),getHeight()-9,p);float bx=joy?jbx:110,by=joy?jby:getHeight()-110;p.setColor(Color.argb(60,255,255,255));c.drawCircle(bx,by,70,p);p.setColor(Color.argb(145,255,255,255));c.drawCircle(bx+jx,by+jy,29,p);}
    private void drawBanner(Canvas c){p.setColor(Color.argb(215,0,0,0));c.drawRoundRect(new RectF(getWidth()/2f-245,22,getWidth()/2f+245,84),18,18,p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(28);t.setColor(Color.rgb(255,235,120));c.drawText(banner,getWidth()/2f,62,t);}
    private void drawChoices(Canvas c){p.setColor(Color.argb(215,5,8,16));c.drawRect(0,0,getWidth(),getHeight(),p);t.setTextAlign(Paint.Align.CENTER);t.setColor(Color.WHITE);t.setTextSize(34);c.drawText("CHOOSE YOUR POWER",getWidth()/2f,90,t);float w=230,h=185,g=24,total=opts.size()*w+(opts.size()-1)*g,sx=(getWidth()-total)/2f,yy=getHeight()*.32f;for(int i=0;i<opts.size();i++){U u=opts.get(i);u.rect=new RectF(sx+i*(w+g),yy,sx+i*(w+g)+w,yy+h);p.setColor(Color.rgb(25,35,57));c.drawRoundRect(u.rect,18,18,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(3);p.setColor(Color.rgb(255,215,90));c.drawRoundRect(u.rect,18,18,p);p.setStyle(Paint.Style.FILL);t.setTextSize(24);t.setColor(Color.rgb(255,235,130));c.drawText(u.title(),u.rect.centerX(),yy+48,t);t.setTextSize(17);t.setColor(Color.WHITE);c.drawText(u.desc(),u.rect.centerX(),yy+90,t);}}
    private void drawDead(Canvas c){p.setColor(Color.argb(225,0,0,0));c.drawRect(0,0,getWidth(),getHeight(),p);t.setTextAlign(Paint.Align.CENTER);t.setTextSize(52);t.setColor(Color.WHITE);c.drawText("GAME OVER",getWidth()/2f,getHeight()/2f-30,t);t.setTextSize(25);c.drawText("Kills "+kills+" • Level "+lv,getWidth()/2f,getHeight()/2f+15,t);c.drawText("Tap to restart",getWidth()/2f,getHeight()/2f+60,t);}

    @Override public boolean onTouchEvent(MotionEvent e){if(dead&&e.getActionMasked()==MotionEvent.ACTION_DOWN){restart();return true;}if(choose&&e.getActionMasked()==MotionEvent.ACTION_DOWN){for(U u:opts)if(u.rect!=null&&u.rect.contains(e.getX(),e.getY())){apply(u.id,false);return true;}return true;}switch(e.getActionMasked()){case MotionEvent.ACTION_DOWN:joy=true;jbx=e.getX();jby=e.getY();jx=jy=0;break;case MotionEvent.ACTION_MOVE:float dx=e.getX()-jbx,dy=e.getY()-jby,d=(float)Math.max(1,Math.hypot(dx,dy)),m=Math.min(70,d);jx=dx/d*m;jy=dy/d*m;break;case MotionEvent.ACTION_UP:case MotionEvent.ACTION_CANCEL:joy=false;jx=jy=0;}return true;}
    private void restart(){es.clear();bs.clear();os.clear();cs.clear();fs.clear();opts.clear();hp=maxHp=120;xp=0;next=12;speed=330;dmg=1;pick=100;armor=0;lv=1;kills=0;ki=1;kame=disc=bomb=kai=ssj=radar=senzu=0;x=getWidth()/2f;y=getHeight()*.58f;start=System.currentTimeMillis();lastSpawn=lastChest=lastBoss=lastKi=lastKame=lastDisc=lastBomb=0;dead=choose=false;show("SURVIVE!");}
    private String time(){long s=(System.currentTimeMillis()-start)/1000;return String.format(Locale.US,"%02d:%02d",s/60,s%60);}private static float cl(float v,float a,float b){return Math.max(a,Math.min(b,v));}private static float dist(float ax,float ay,float bx,float by){return(float)Math.hypot(ax-bx,ay-by);}
    static class E{float x,y,hp,r,sp,touch,cd;int type;boolean boss;E(float x,float y,int type,float hp,float r,float sp,float touch,boolean boss){this.x=x;this.y=y;this.type=type;this.hp=hp;this.r=r;this.sp=sp;this.touch=touch;this.boss=boss;}}
    static class B{int type;float x,y,vx,vy,r,d,life=2.5f;int pierce,hits;B(int type,float x,float y,float vx,float vy,float r,float d,int pierce){this.type=type;this.x=x;this.y=y;this.vx=vx;this.vy=vy;this.r=r;this.d=d;this.pierce=pierce;}}
    static class O{float x,y,v;O(float x,float y,float v){this.x=x;this.y=y;this.v=v;}}static class C{float x,y;C(float x,float y){this.x=x;this.y=y;}}static class F{float x,y,life=.7f;String s;F(float x,float y,String s){this.x=x;this.y=y;this.s=s;}}
    static class U{String id;RectF rect;U(String id){this.id=id;}String title(){switch(id){case"ki":return"Ki Blast";case"kame":return"Kamehameha";case"disc":return"Kienzan";case"bomb":return"Genkidama";case"kai":return"Kaioken";case"senzu":return"Senzu Bean";case"radar":return"Dragon Radar";default:return"Super Saiyan";}}String desc(){switch(id){case"ki":return"More blasts & damage";case"kame":return"Powerful piercing beam";case"disc":return"Spinning piercing disc";case"bomb":return"Huge explosive attack";case"kai":return"Move faster";case"senzu":return"Heal + max HP";case"radar":return"Pull XP from farther";default:return"Transform & power up";}}}
}
